spring:
  profiles:
    active: @spring.profiles.active@
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa4x8n4hyfnUKjug4x6
            client-secret: AGHGclJc2V0NzPzt4OcirWZ8eq2bmTeKPs1hhSyf
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-397378.okta.com/oauth2/default


